### PR TITLE
[FIX] start ssh server when `START_SSH` build-env-arg is supplied (deployv)

### LINKED ISSUE #200: When using --deployv option and providing the $START_SSH variable, the SSH service is not started
Previously, we supported the `$START_SSH="1"` variable to indicate the SSH service to be started automatically on created containers.

Since we now use the `--deployv` option, such variable doesn't work anymore, I'm guessing due to the used image.

CC @antonag32 @moylop260

### PR DESCRIPTION
**Pull request by antonag32**
Fixes #200.

When supplying t2d the "START_SSH" argument during setup it is expected
that the generated image will automatically start running  the ssh
service.

This was not happening when using --deployv, it has been fixed by
adding the logic to autostart the server in the entrypoint for it.

Since the SSH server can only be started by root, the other commands
in the entrypoint have been modified to use the correct user if the
image is being run as root.

The same support has been given to ODOO and PSQL services. They start by
default but this can be avoided by providing a falsy value for
START_ODOO and START_PSQL respectively.

### CODE REVIEW

**Comment by antonag32** [comment]
@luisg123v @moylop260 

Can you review please?

File: src/travis2docker/templates/entrypoint_deployv.sh [hunk 1]
```diff
@@ -61,7 +62,7 @@ def list_modules(modules_path):
     excluded_modules = set([module.strip() for module in os.environ.get("EXCLUDE", "").split(",") if module.strip()])
     for i in os.listdir(main_repo_path):
         if i in excluded_modules:
-          continue
+            continue
```
Comment (luisg123v) [inline src/travis2docker/templates/entrypoint_deployv.sh:65]: Could you fix lints in a separate commit, please?

File: src/travis2docker/templates/entrypoint_deployv.sh [hunk 2]
```diff
@@ -85,6 +90,10 @@ def start_odoo():
         "-XtAc",
         "SELECT 1 FROM res_users LIMIT 1;",
     ]
+    if is_root():
+      cmd = ["sudo", "-u", "odoo"] + cmd
```
Comment (luisg123v) [inline src/travis2docker/templates/entrypoint_deployv.sh:94]: wrong indentation

File: src/travis2docker/templates/entrypoint_deployv.sh [hunk 3]
```diff
@@ -101,6 +110,12 @@ def start_odoo():
     subprocess.call(cmd)
 
 
+def start_ssh():
+    if os.environ.get("START_SSH", False) and is_root():
```
Comment (luisg123v) [inline src/travis2docker/templates/entrypoint_deployv.sh:114]: - Superfluous default value for `get`
- Since we're already adding a variable to start SSH, what do you think about adding two more ones to start PSQL and ODoo? (Whose default value would be `True`, of course)

**Review by luisg123v — CHANGES_REQUESTED** [review]

**Comment by luisg123v** [comment]
Description:

When you say "build arg", I think you mean env var

**Comment by antonag32** [comment]
> Description:
> 
> When you say "build arg", I think you mean env var

I guess the technically correct way would be `build-env-arg` since I am referring to the command line arguments used to set `START_SSH`.

File: src/travis2docker/templates/entrypoint_deployv.sh (hunk 3 above)
Comment (antonag32) [reply src/travis2docker/templates/entrypoint_deployv.sh:114]: I guess we can add it. The ENV variables would then be something like: `NO_AUTO_ODOO`? Or what would be an appropriate name for it?

Also if `NO_AUTO_POSTGRES` is set, but Odoo is set to autostart, should we just let it naturally fail, or watch out for it?

Comment (luisg123v) [reply src/travis2docker/templates/entrypoint_deployv.sh]: they would be `START_ODOO` and `START_PSQL`

ANd the code inside those methods would look something like:

```
 def start_psql():
    if not str2bool(os.environ.get("START_PSQL", True)):
        return
```

**Comment by antonag32** [comment]
I made the corrections @luisg123v.

Should the support for not starting postgresql and odoo be made on a different PR? Also I personally think having the option to not start odoo would be more helpful than the option of not starting postgresql.

Sometimes I want to run Odoo with different arguments specially when developing tests, and having it run as a service gets in the way. However postgres has never gotten in the way, so I wonder if it would be really useful to have the option to not start it.

File: src/travis2docker/templates/entrypoint_deployv.sh (hunk 3 above)
Comment (luisg123v) [reply src/travis2docker/templates/entrypoint_deployv.sh]: > Also if NO_AUTO_POSTGRES is set, but Odoo is set to autostart, should we just let it naturally fail, or watch out for it?

That's a valid combination. Actually, that's the one I (and also the migration team) use, because we don't use the PSQL server inside the container but the local one. That because we need to connect to the same database from several containers.

For more info, check [this documentation](https://git.vauxoo.com/vauxoo/documentation/-/wikis/Connect-to-PostgreSQL-from-Container)

**Comment by moylop260** [comment]
@luisg123v 

Could you check it, please?

**Comment by antonag32** [comment]
I think the other two options (`START_ODOO` and `START_POSTGRESQL`) are still missing but I don't know if we should add it here or in a new MR.

**Comment by luisg123v** [comment]
@antonag32,

> I think the other two options (START_ODOO and START_POSTGRESQL) are still missing but I don't know if we should add it here or in a new MR.

I think it could be here. All options are new and behave similarly

**Comment by antonag32** [comment]
@luisg123v sorry for the delay, I implemented the two other arguments , START_ODOO and START_PSQL.

Can you review?

cc @moylop260

**Review by luisg123v — APPROVED** [review]
LGTM :+1:
